/**
 * Headless autopilot runner (Node >= 20). Runs the same tick as the browser, signing with a
 * session key that the owner authorised via the cockpit (authz + feegrant). The owner's key is
 * never needed here.
 *
 *   npm run autopilot -- --owner inj1... --key-file ./session.key [--interval 60] [--webhook https://ntfy.sh/topic]
 *                        [--state ./autopilot-state.json] [--strategy ./strategy.json] [--dry-run] [--once]
 *
 * The session key file contains the hex private key generated by the cockpit's "Export for the
 * headless runner" button (or by `npm run session -- generate`). Keep it as private as a wallet key
 * for the duration of the grant; it can only do what the grant allows, and the grant expires.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { LcdClient } from '../src/chain/lcd'
import { DEFAULT_LCD_HOSTS, isInjAddress } from '../src/config/chain'
import { getTrend } from '../src/market/trend'
import { DEFAULT_STRATEGY, parseStrategy, type StrategyConfig } from '../src/strategy/types'
import { AlertThrottle, DEFAULT_ALERT_INTERVALS, DEFAULT_AUTOPILOT, newTickState, runTick, type Alert } from '../src/execution/autopilot'
import { createChainPorts } from '../src/execution/chainPorts'
import { protocolFingerprint } from '../src/execution/fingerprint'
import { priceMinutesAgo } from '../src/execution/guards'
import { fetchGrantStatus } from '../src/execution/session'
import { SessionSigner, generateSessionKey, sessionFromHex } from '../src/execution/signer'

function arg(name: string, def?: string): string | undefined {
  const i = process.argv.indexOf(`--${name}`)
  return i >= 0 ? process.argv[i + 1] : def
}
const flag = (name: string) => process.argv.includes(`--${name}`)

if (process.argv[2] === 'generate') {
  const k = generateSessionKey()
  const file = arg('out', './session.key')!
  writeFileSync(file, k.privateKeyHex + '\n', { mode: 0o600 })
  console.log(`session key written to ${file}\naddress: ${k.address}\n\nGrant it permissions in the cockpit (Autopilot -> Session -> "Use an existing session address"), then run:\n  npm run autopilot -- --owner <your inj1 address> --key-file ${file}`)
  process.exit(0)
}

const owner = arg('owner')
const keyFile = arg('key-file')
const keyHex = process.env.NLC_SESSION_KEY ?? (keyFile && existsSync(keyFile) ? readFileSync(keyFile, 'utf8').trim() : undefined)
if (!owner || !isInjAddress(owner) || !keyHex) {
  console.error('usage: npm run autopilot -- --owner inj1... --key-file ./session.key [--interval 60] [--webhook URL] [--state FILE] [--strategy FILE] [--dry-run] [--once]\n       npm run autopilot -- generate [--out ./session.key]')
  process.exit(2)
}
const intervalSec = Math.max(20, parseInt(arg('interval', '60')!, 10) || 60)
const webhook = arg('webhook')
const stateFile = arg('state', './autopilot-state.json')!
const dryRun = flag('dry-run')
const once = flag('once')
let strategy: StrategyConfig = DEFAULT_STRATEGY
const strategyFile = arg('strategy')
if (strategyFile) strategy = parseStrategy(readFileSync(strategyFile, 'utf8'))

const lcd = new LcdClient({ hosts: DEFAULT_LCD_HOSTS })
const session = sessionFromHex(keyHex)
const signer = new SessionSigner({ lcd, ownerAddress: owner, session, useFeegrant: true })
const autopilot = { ...DEFAULT_AUTOPILOT, enabled: !dryRun }
const state = newTickState()
try {
  if (existsSync(stateFile)) {
    const s = JSON.parse(readFileSync(stateFile, 'utf8'))
    state.lastBuyAtMs = s.lastBuyAtMs ?? null
    state.continueDown = !!s.continueDown
    state.paramChangeLockUntilMs = s.paramChangeLockUntilMs ?? null
    state.lastFingerprint = s.lastFingerprint ?? null
  }
} catch {
  /* fresh */
}
const throttle = new AlertThrottle(DEFAULT_ALERT_INTERVALS)
let stopping = false
process.on('SIGINT', () => {
  console.log('\nstop requested - finishing the current round')
  stopping = true
})
process.on('SIGTERM', () => {
  stopping = true
})

const ts = () => new Date().toISOString().slice(11, 19)
async function alert(a: Alert) {
  console.log(`${ts()} [${a.level}] ${a.title} - ${a.body.replace(/\n/g, ' | ')}`)
  if (webhook) {
    try {
      await fetch(webhook, { method: 'POST', headers: { Title: a.title.replace(/[^\x20-\x7e]/g, ''), Priority: a.level === 'urgent' ? 'urgent' : a.level === 'warn' ? 'high' : 'default' }, body: a.body, signal: AbortSignal.timeout(8000) })
    } catch (e) {
      console.log(`${ts()} webhook failed: ${String(e).slice(0, 80)}`)
    }
  }
}

const ports = createChainPorts({
  lcd,
  signer,
  shouldStop: () => stopping,
  log: (e) => console.log(`${ts()}   ${e.step}: ${e.info}${e.txHash ? ` (${e.txHash})` : ''}`),
})

let fingerprint: string | null = null
let fingerprintAt = 0

async function main() {
  console.log(`owner ${owner}\nsession ${session.address}\ninterval ${intervalSec} s · ${dryRun ? 'DRY RUN (never executes)' : 'LIVE'} · strategy "${strategy.name}"`)
  const grants = await fetchGrantStatus(lcd, owner!, session.address)
  console.log(`grants: wasm ${grants.wasm.ok ? 'ok' : 'MISSING'} · spot ${grants.spot.ok ? 'ok' : 'MISSING'} · feegrant ${grants.feegrant.ok ? `ok (${grants.feegrant.remainingInj?.toFixed(3)} INJ left)` : 'MISSING'} · expires ${grants.expiresAt ?? '-'}`)
  if (!grants.complete && !dryRun) {
    console.error('grants incomplete - create them in the cockpit first (Autopilot -> Session -> Grant). Exiting.')
    process.exit(1)
  }
  while (!stopping) {
    const t0 = Date.now()
    try {
      if (t0 - fingerprintAt > 10 * 60_000) {
        fingerprint = await protocolFingerprint(lcd)
        fingerprintAt = t0
      }
      const [trend, priceThen] = await Promise.all([getTrend({ smaDays: strategy.trendFilter.smaDays, panicPct: strategy.trendFilter.panicPct }), priceMinutesAgo(autopilot.buyHoldMin).catch(() => null)])
      const r = await runTick({ ports, strategy, autopilot, state, paused: false, trend, priceThen, fingerprint })
      console.log(`${ts()} ${r.decision.action.toUpperCase()} · ${r.decision.reason.slice(0, 160)} · health ${r.status.health.toFixed(3)} LTV ${(r.status.ltv * 100).toFixed(1)} % · INJ $${r.status.injPrice.toFixed(3)}${r.execStatus ? ` · ${r.execStatus}` : ''} (${(r.durationMs / 1000).toFixed(1)} s)`)
      for (const a of r.alerts) if (throttle.allow(a.key, Date.now())) await alert(a)
      writeFileSync(stateFile, JSON.stringify({ lastBuyAtMs: state.lastBuyAtMs, continueDown: state.continueDown, paramChangeLockUntilMs: state.paramChangeLockUntilMs, lastFingerprint: state.lastFingerprint, updatedAt: new Date().toISOString() }, null, 2))
      if (once) break
      const wait = r.executed && r.execStatus === 'deferred' ? Math.min(intervalSec, 20) : intervalSec
      await new Promise((res) => setTimeout(res, Math.max(0, wait * 1000 - (Date.now() - t0))))
    } catch (e) {
      console.log(`${ts()} tick failed: ${String((e as Error)?.message ?? e).slice(0, 200)}`)
      if (throttle.allow('monitor-error', Date.now())) await alert({ key: 'monitor-error', level: 'warn', title: 'Autopilot tick failed', body: String(e).slice(0, 300) })
      if (once) break
      await new Promise((res) => setTimeout(res, intervalSec * 1000))
    }
  }
  console.log('stopped')
}

void main()
